### ISSUE TITLE
Logging suggestion for polling state in new code

### ISSUE THREAD

**Issue by knuckleheadsmiff** [knuckleheadsmiff/homebridge-garagedoor-ryobi#17]
The logs are getting verbose with two lines, the “polling state” and then the actual state. If not in debug mode it would be better to only log the state when it is different from what was last logged. In debug mode what you have is OK. Anyway just a suggestion to reduce log noise.

**Comment by knuckleheadsmiff** [comment]
![49A438CC-BAB1-47B6-A8D2-9D11F506A487](https://user-images.githubusercontent.com/54040140/115939155-0b5f4a80-a452-11eb-9360-3f0c3fe33d5d.jpeg)

**Comment by knuckleheadsmiff** [comment]
It is less verbose (1 line instead of 2). 

I was thinking also perhaps only logging normally when the state differs from the last logged state but in debug log every time the state of read like it does now. Wdyt?

I’ll let you decide.

**Comment by andyedinborough** [comment]
Sounds good. I'll make that change.
