### ISSUE TITLE
Log Error - UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by fatkid98** [knuckleheadsmiff/homebridge-garagedoor-ryobi#18]
Since the 0.3.2 update, I'm getting an UnhandledPromiseRejectionWarning. I can uninstall the plugin and reinstall it and it'll work fora little bit, but then goes back to the error. Attached is a screenshot of the log. I am running the plugin using Hoobs on a RPi. 

<img width="1757" alt="Screen Shot 2021-04-24 at 1 43 44 PM" src="https://user-images.githubusercontent.com/83135209/115968077-f4793080-a503-11eb-9c73-5a420aaa4953.png">

**Comment by knuckleheadsmiff** [comment]
I see it too although things still seem to work. I’ll forward to Andy to look into. 

![62F10A3A-7806-4E79-BA22-C55B643369A2](https://user-images.githubusercontent.com/54040140/115969665-eb339800-a4f2-11eb-880f-764475434068.jpeg)

**Comment by fatkid98** [comment]
What I have noticed is that whatever state the door was in (open or closed) when the error shows up will continue to show that way in HomeKit, even if the door is in a different state.

**Comment by knuckleheadsmiff** [comment]
Yup, it seems as the code that polls the current state every 90 seconds is not kicked off again when the error happens. It will be looked into. Thanks.

**Comment by andyedinborough** [comment]
I've got a fix nearly ready. Just adding some unit tests.
